=== sqoor/pipeline1-project/invoices-schema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="invoices">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="invoice">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="patient">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="phone">
                      <xs:complexType>
                        <xs:attribute name="type" type="xs:string" use="required" />
                        <xs:attribute name="number" type="xs:string" use="required" />
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="address">
                      <xs:complexType>
                        <xs:attribute name="type" type="xs:string" use="required" />
                        <xs:attribute name="line1" type="xs:string" use="required" />
                        <xs:attribute name="city" type="xs:string" use="required" />
                        <xs:attribute name="state" type="xs:string" use="required" />
                        <xs:attribute name="zip" type="xs:unsignedShort" use="required" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="firstname" type="xs:string" use="required" />
                  <xs:attribute name="familyname" type="xs:string" use="required" />
                  <xs:attribute name="SSN" type="xs:unsignedInt" use="required" />
                </xs:complexType>
              </xs:element>
              <xs:element name="insurance">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="phone">
                      <xs:complexType>
                        <xs:attribute name="number" type="xs:string" use="required" />
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="address">
                      <xs:complexType>
                        <xs:attribute name="type" type="xs:string" use="required" />
                        <xs:attribute name="line1" type="xs:string" use="required" />
                        <xs:attribute name="city" type="xs:string" use="required" />
                        <xs:attribute name="state" type="xs:string" use="required" />
                        <xs:attribute name="zip" type="xs:unsignedInt" use="required" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="name" type="xs:string" use="required" />
                  <xs:attribute name="plannumber" type="xs:string" use="required" />
                  <xs:attribute name="planname" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
              <xs:element maxOccurs="unbounded" name="procedure">
                <xs:complexType>
                  <xs:attribute name="code" type="xs:unsignedShort" use="required" />
                  <xs:attribute name="name" type="xs:string" use="required" />
                  <xs:attribute name="cost" type="xs:decimal" use="required" />
                  <xs:attribute name="insurance_estimate" type="xs:decimal" use="required" />
                </xs:complexType>
              </xs:element>
              <xs:element minOccurs="0" name="man">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="cat" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="number" type="xs:unsignedShort" use="required" />
            <xs:attribute name="date" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== sqoor/pipeline1-project/invoices-data.xml
<?xml version="1.0"?>
<invoices xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="invoices-schema.xsd">
    <invoice number="12384" date="January 19, 2021">
        <patient firstname="Abdullah" familyname="Daqdoqa" SSN="123123123">
            <phone type="home" number="06-123456" />
            <phone type="mobile" number="07-49001345" />
            <address type="home" line1="2255 Street" city="Valbonne" state="" zip="06560" />
        </patient>
        <insurance name="Cigna Global" plannumber="A1" planname="First degree">
            <phone number="099-987564321" />
            <address type="business" line1="1234 Street" city="Nice" state="Alpes-Maritimes" zip="06123" />
        </insurance>
        <procedure code="115" name="Cleaning ears" cost="50.00" insurance_estimate="50.00" />
        <procedure code="161" name="Breaces checkup" cost="100.00" insurance_estimate="80.00" />
        <procedure code="120" name="Acne teatment" cost="80.00" insurance_estimate="60.00" />
    </invoice>
    <invoice number="12385" date="January 19, 2021">
        <patient firstname="Jack" familyname="Blanc" SSN="123456765">
            <phone type="home" number="123-4562245" />
            <address type="home" line1="123 Street" city="Paris" state="Île-de-France" zip="12343" />
        </patient>
        <insurance name="April International" plannumber="3455" planname="Second degree full package">
            <phone number="064-87654321" />
            <address type="business" line1="1234 Street" city="Paris" state="Île-de-France" zip="54321" />
        </insurance>
        <procedure code="168" name="Teeth removal" cost="100.00" insurance_estimate="70.00" />
        <procedure code="256" name="Eyes checkup" cost="45.00" insurance_estimate="45.00" />
    </invoice>
    <invoice number="12386" date="January 19, 2021">
        <patient firstname="Sarah" familyname="Francois" SSN="123456345">
            <phone type="home" number="876-31654891" />
            <address type="home" line1="9982 Street" city="Lyon" state="Auvergne-Rhône-Alpes" zip="42145" />
        </patient>
        <insurance name="Foyer Global Health" plannumber="12345" planname="Third dgree for minors">
            <phone number="168-98756541" />
            <address type="business" line1="6579 Street" city="Lyon" state="Auvergne-Rhône-Alpes" zip="468130" />
        </insurance>
        <procedure code="684" name="Diabetes treatment" cost="60.00" insurance_estimate="40.00" />
        <procedure code="3356" name="flu treatment" cost="85.00" insurance_estimate="85.00" />
        <procedure code="3356" name="Annual checkup" cost="100.00" insurance_estimate="160.00" />
    </invoice>
</invoices>
